apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
spec:
  type: NodePort
  selector:
    app: does-not-match
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
